[package]
name = "pnlx-risc0-batch-match-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
ark-bn254.workspace = true
ark-ff.workspace = true
hex.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
pso-poseidon.workspace = true
serde.workspace = true
sha2.workspace = true

[dev-dependencies]
serde_json.workspace = true
