services:
  merkl-matcher-provider:
    image: ${MERKL_MATCHER_PROVIDER_IMAGE}
    ports:
      - "4103:4103"
    environment:
      NODE_ENV: production
      MATCHER_PROVIDER_PORT: "4103"
      MATCHER_PROVIDER_TOKEN: ${MATCHER_PROVIDER_TOKEN}
      MERKL_RUNTIME_DIR: /var/lib/merkl
      THRESHOLD_SHARE_NODE_IDS: ${THRESHOLD_SHARE_NODE_IDS}
      THRESHOLD_SHARE_THRESHOLD: ${THRESHOLD_SHARE_THRESHOLD}
      THRESHOLD_SHARE_STORE_DIR: /var/lib/merkl/threshold-shares
    volumes:
      - merkl-matcher-provider:/var/lib/merkl

volumes:
  merkl-matcher-provider:
